### ISSUE TITLE
catkin_create_qt_project creates wrong package.xml if deps given

### ISSUE THREAD

**Issue by strothmw** [stonier/qt_ros#13] opened 2014-08-14 07:40 UTC
If i run catkin_create_qt_project my_project cv_brigde sensor_msgs it adds to package.xml for deps:

  <depend package="cv_brigde"/>
  <depend package="sensor_msgs"/>

rather than

  <build_depend>cv_brigde</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <run_depend>cv_brigde</run_depend>
  <run_depend>sensor_msgs</run_depend>

I am under ros hydro with ubuntu 12.04 64 bit

**Comment by stonier** [comment] 2014-08-15 04:24
Duplicate of #14.

**Closed as completed by stonier** 2014-08-15 04:24 UTC
